<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
		<PackageReference Include="BenchmarkDotNet.TestAdapter" Version="0.15.8" />
		<PackageReference Include="Testcontainers.Oracle" Version="4.10.0" />
		<PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.100" />
	</ItemGroup>

	<ItemGroup Label="unit test support">
		<PackageReference Include="coverlet.collector" Version="*" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" />
		<PackageReference Include="NUnit" Version="*" />
		<PackageReference Include="NUnit.Analyzers" Version="*" />
		<PackageReference Include="NUnit3TestAdapter" Version="*" />
		<Using Include="NUnit.Framework" />
	</ItemGroup>

	<PropertyGroup>
		<EnableNUnitRunner>true</EnableNUnitRunner>
	</PropertyGroup>

</Project>
